import os
import json
import mimetypes
from pydantic import BaseModel, Field
from google import genai
from google.genai import types
from dotenv import load_dotenv

# Load environment variables from .env file in the current directory
current_dir = os.path.dirname(os.path.abspath(__file__))
env_path = os.path.join(current_dir, '.env')
load_dotenv(env_path)

# Setup Gemini API
api_key = os.getenv("GEMINI_API_KEY")
if not api_key:
    print("Warning: GEMINI_API_KEY environment variable not set. Functions will fail when called.")
    client = None
else:
    client = genai.Client(api_key=api_key)
text_model_name = "gemini-3.1-flash-lite"
vision_model_name = "gemini-3.1-flash-lite" 

# Define structured output schema for text detection
class DetectionResult(BaseModel):
    label: str = Field(description="Must be 'Fake' if AI-generated, or 'Real' if human-written")
    score: float = Field(description="Confidence score between 0.0 and 1.0")
    reasoning: str = Field(description="Brief explanation of why this classification was chosen")

# Define structured output schema for image detection
class ImageDetectionResult(BaseModel):
    label: str = Field(description="Must be 'AI Generated' if the image is AI-generated, or 'Real' if it's a real photograph")
    score: float = Field(description="Confidence score between 0.0 and 1.0")
    reasoning: str = Field(description="Detailed explanation of why this classification was chosen, including specific visual artifacts or patterns observed")

SYSTEM_INSTRUCTION = """
You are an expert AI writing detector. Analyze the user's text and determine if it is likely written by a human or generated by an AI.
Rely on established signs of AI writing, such as:
1. High density of "AI vocabulary": words like "delve", "tapestry", "multifaceted", "testament", "orchestrate", "realm", "crucial", "underscores", "moreover", "navigating the landscape".
2. Formulaic structures: opening with broad historical/general statements, or ending with outline-like summaries (e.g. "In conclusion").
3. Superficial analysis: perfectly balanced paragraphs that lack genuine insight, specific detail, or strong editorial opinions.
4. Overuse of transitional adverbs and parallelisms (e.g. "Not just X, but also Y").

Provide your output strictly matching the requested JSON schema.
"""

IMAGE_SYSTEM_INSTRUCTION = """
You are an expert AI image detector. Analyze the provided image and determine if it is likely AI-generated or a real photograph.
Look for common signs of AI-generated images such as:
1. Unnatural textures or patterns in skin, hair, or clothing
2. Inconsistent lighting or shadows
3. Distorted or impossible geometry (extra fingers, melted objects, etc.)
4. Overly perfect or symmetrical compositions
5. Unusual artifacts or blurring in certain areas
6. Inconsistent depth of field
7. Strange reflections or missing environmental details
8. Text or logos that appear distorted or nonsensical

Provide your output strictly matching the requested JSON schema with detailed reasoning about specific visual elements you observed.
"""

def analyze_text(text):
    """
    Analyze text to determine if it's AI-generated or human-written.
    
    Args:
        text: The text content to analyze
        
    Returns:
        Dictionary with label, score, and reasoning
    """
    if not client:
        return {
            "label": "Error",
            "score": 0.0,
            "reasoning": "GEMINI_API_KEY not set. Please configure your API key."
        }
    
    try:
        response = client.models.generate_content(
            model=text_model_name, 
            contents=text,
            config=types.GenerateContentConfig(
                system_instruction=SYSTEM_INSTRUCTION,
                response_mime_type="application/json",
                response_schema=DetectionResult,
                temperature=0.1
            )
        )
        return json.loads(response.text)
    except Exception as e:
        print(f"Error analyzing text: {e}")
        return {
            "label": "Error",
            "score": 0.0,
            "reasoning": f"Failed to analyze text: {str(e)}"
        }

def analyze_image(image_path):
    """
    Analyze an image to determine if it's AI-generated or real.
    
    Args:
        image_path: Path to the image file to analyze
        
    Returns:
        Dictionary with label, score, and reasoning
    """
    if not client:
        return {
            "label": "Error",
            "score": 0.0,
            "reasoning": "GEMINI_API_KEY not set. Please configure your API key."
        }
    
    try:
        # Detect the mime type of the image
        mime_type, _ = mimetypes.guess_type(image_path)
        if not mime_type or not mime_type.startswith('image/'):
            mime_type = 'image/jpeg'  # Fallback to jpeg if detection fails
        
        # Read the image file
        with open(image_path, "rb") as image_file:
            image_data = image_file.read()
        
        # Create a Part with the image data
        image_part = types.Part.from_bytes(
            data=image_data,
            mime_type=mime_type
        )
        
        response = client.models.generate_content(
            model=vision_model_name,
            contents=[image_part],
            config=types.GenerateContentConfig(
                system_instruction=IMAGE_SYSTEM_INSTRUCTION,
                response_mime_type="application/json",
                response_schema=ImageDetectionResult,
                temperature=0.1
            )
        )
        
        return json.loads(response.text)
        
    except Exception as e:
        print(f"Error analyzing image: {e}")
        return {
            "label": "Error",
            "score": 0.0,
            "reasoning": f"Failed to analyze image: {str(e)}"
        }

def analyze_image_from_bytes(image_data, mime_type="image/jpeg"):
    """
    Analyze an image from bytes data (for Streamlit uploaded files).
    
    Args:
        image_data: Bytes data of the image
        mime_type: MIME type of the image (default: image/jpeg)
        
    Returns:
        Dictionary with label, score, and reasoning
    """
    if not client:
        return {
            "label": "Error",
            "score": 0.0,
            "reasoning": "GEMINI_API_KEY not set. Please configure your API key."
        }
    
    try:
        # Create a Part with the image data
        image_part = types.Part.from_bytes(
            data=image_data,
            mime_type=mime_type
        )
        
        response = client.models.generate_content(
            model=vision_model_name,
            contents=[image_part],
            config=types.GenerateContentConfig(
                system_instruction=IMAGE_SYSTEM_INSTRUCTION,
                response_mime_type="application/json",
                response_schema=ImageDetectionResult,
                temperature=0.1
            )
        )
        
        return json.loads(response.text)
        
    except Exception as e:
        print(f"Error analyzing image: {e}")
        return {
            "label": "Error",
            "score": 0.0,
            "reasoning": f"Failed to analyze image: {str(e)}"
        }
        
def filter_dataset_batch(text_list, threshold=0.70):
    if not client:
        print("GEMINI_API_KEY not set. Cannot filter dataset.")
        return text_list
    
    human_texts = []
    
    for idx, text in enumerate(text_list):
        print(f"Analyzing text {idx+1}/{len(text_list)}...")
        
        try:
            response = client.models.generate_content(
                model=text_model_name,
                contents=text,
                config=types.GenerateContentConfig(
                    system_instruction=SYSTEM_INSTRUCTION,
                    response_mime_type="application/json",
                    response_schema=DetectionResult,
                    temperature=0.1
                )
            )
            
            result = json.loads(response.text)
            
            is_ai = result["label"] == "Fake" and result["score"] >= threshold
            
            if not is_ai:
                human_texts.append(text)
                
        except Exception as e:
            print(f"Error processing text: {e}")
            # Failsafe: keep the text if API fails
            human_texts.append(text)
            
    return human_texts

# --- Example Usage on Your Dataset ---
if __name__ == "__main__":
    
    # 2. Dummy data
    raw_texts = [
        "In today's fast-paced digital landscape, it is imperative to leverage synergistic paradigms. This multifaceted tapestry of innovation underscores a crucial paradigm shift.",
        "I spilled coffee on my keyboard this morning and now the spacebar is sticky.",
        "Cats are small, intelligent mammals that are commonly kept as pets. They are independent, curious, and playful animals with excellent hearing..."
    ]

    print("Filtering dataset using Gemini...")
    
    cleaned_texts = filter_dataset_batch(raw_texts, threshold=0.70)

    print(f"\nOriginal count: {len(raw_texts)}")
    print(f"Cleaned count: {len(cleaned_texts)}")
    
    print("\n--- Texts that passed the filter ---")
    for text in cleaned_texts:
        print(f"[PASS] {text[:50]}...")

    